# Generated by Django 4.0.3 on 2022-03-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countryclub_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='clubmembers',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='clubmembers',
            name='is_employee',
        ),
    ]
